### ISSUE TITLE
The function "foo" should be called on each calculation for consistency.

### ISSUE THREAD

**Issue by CryptoCashCashoo** [tradingview/pine_script_docs#151]
Hi,

When the execution of a funciton is set in a conditional block, the compiler trigger a warning about a calculation consistency problem:
![image](https://user-images.githubusercontent.com/83143288/117017335-ceb60d80-acf3-11eb-95ce-df399627213b.png)

What consistency does refer this warning? Low performance, low accuracy, some obscure bug that will not execute that function?

Thanks!

**Comment by LucFF** [comment]
See the Pine usrman: https://www.tradingview.com/pine-script-docs/en/v4/language/Functions_and_annotations.html#why-this-behavior
